POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "jane",
  "email": "jane@mail.com",
  "phoneNumber": "2250102030407",
  "password": "Password123#"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "djen",
  "password": "Password123#"
}