
### GET ALL LOBBIES

GET http://localhost:3000/lobby
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJzdWIiOiJjNzEwM2JkYS1hZWZhLTQ1OTktODdhYi0wOTBjYzQyZjk1ZjAiLCJpYXQiOjE3Mjk1MzEwOTEsImV4cCI6MTcyOTUzNDY5MX0.hMV6I4xnBafouVqQV0uY6kVQwj7iQYmNPMJ6Ly9fcfo

### CREATE LOBBY

POST http://localhost:3000/lobby/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJzdWIiOiJjNzEwM2JkYS1hZWZhLTQ1OTktODdhYi0wOTBjYzQyZjk1ZjAiLCJpYXQiOjE3Mjk1MzEwOTEsImV4cCI6MTcyOTUzNDY5MX0.hMV6I4xnBafouVqQV0uY6kVQwj7iQYmNPMJ6Ly9fcfo

{
  "name": "Warrior of the North",
  "userId": "c7103bda-aefa-4599-87ab-090cc42f95f0",
  "maxParticipants": 4
}

### JOIN LOBBY

POST http://localhost:3000/lobby/e7aa6b7e-8019-4fb9-8be6-022d90f0b339/join
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphY29iIiwic3ViIjoiZTYyMDE3YjktMDE1MC00YzdhLTgwZWItNjNlZjVjZjQ2MmUyIiwiaWF0IjoxNzMwMjE4NjE2LCJleHAiOjE3MzAyMjIyMTZ9.cj7uxCbAXhzsgMO2Pu-T2k8bnlKapJl0tNzqDGGHvQU

### LEAVE LOBBY

POST http://localhost:3000/lobby/e7aa6b7e-8019-4fb9-8be6-022d90f0b339/leave
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphY29iIiwic3ViIjoiZTYyMDE3YjktMDE1MC00YzdhLTgwZWItNjNlZjVjZjQ2MmUyIiwiaWF0IjoxNzMwMjE4NjE2LCJleHAiOjE3MzAyMjIyMTZ9.cj7uxCbAXhzsgMO2Pu-T2k8bnlKapJl0tNzqDGGHvQU

### KICK PLAYER FROM LOBBY
POST http://localhost:3000/lobby/e7aa6b7e-8019-4fb9-8be6-022d90f0b339/kick
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphY29iIiwic3ViIjoiZTYyMDE3YjktMDE1MC00YzdhLTgwZWItNjNlZjVjZjQ2MmUyIiwiaWF0IjoxNzMwMjE4NjE2LCJleHAiOjE3MzAyMjIyMTZ9.cj7uxCbAXhzsgMO2Pu-T2k8bnlKapJl0tNzqDGGHvQU

### GET LOBBY

GET http://localhost:3000/lobby/e7aa6b7e-8019-4fb9-8be6-022d90f0b339
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRqZW4iLCJzdWIiOiI4ZWFlMjNmMS00Y2NjLTRmZmItYWZjNS1jYWViZmU2Y2JjZGYiLCJpYXQiOjE3MzAyMTg1MzksImV4cCI6MTczMDIyMjEzOX0.apNU1Tpmhp91A3nkvLQ2Mpsz9cg5xLDhHJs-7oBMuPY
