
GET http://localhost:3000/lobby
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJzdWIiOiI1NzRkMzYwYS1mYzIxLTQ0YmYtOGQxMi1lZDY2YzY5OWFkZjQiLCJpYXQiOjE3Mjk1Mjc5ODcsImV4cCI6MTcyOTUzMTU4N30.HhadvtvVE9FzYAveiZVZmVStoORW_17jePYnXQmIpyM

###

POST http://localhost:3000/lobby/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJzdWIiOiI1NzRkMzYwYS1mYzIxLTQ0YmYtOGQxMi1lZDY2YzY5OWFkZjQiLCJpYXQiOjE3Mjk1Mjc5ODcsImV4cCI6MTcyOTUzMTU4N30.HhadvtvVE9FzYAveiZVZmVStoORW_17jePYnXQmIpyM

{
  "name": "MyNewLobby",
  "userId": "80f1d05f-9faf-4747-b97e-739badebd3f9"
}

###

POST http://localhost:3000/lobby/2ca82a32-7249-4951-a55f-0adc1c3772c5/join
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJzdWIiOiI1NzRkMzYwYS1mYzIxLTQ0YmYtOGQxMi1lZDY2YzY5OWFkZjQiLCJpYXQiOjE3Mjk1Mjc5ODcsImV4cCI6MTcyOTUzMTU4N30.HhadvtvVE9FzYAveiZVZmVStoORW_17jePYnXQmIpyM

###

GET http://localhost:3000/lobby/9f583c1c-8f1e-4025-88d8-4e2b21134f74
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJzdWIiOiI1NzRkMzYwYS1mYzIxLTQ0YmYtOGQxMi1lZDY2YzY5OWFkZjQiLCJpYXQiOjE3Mjk1Mjc5ODcsImV4cCI6MTcyOTUzMTU4N30.HhadvtvVE9FzYAveiZVZmVStoORW_17jePYnXQmIpyM
